name: Prepare release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      RELEASE_NAME: Upcoming release
      TAG_NAME: vNext
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Taxonomy Service
        run: |
          cd tools/TaxonomyService/TaxonomyService
          mv appsettings.release.json appsettings.json
          dotnet build -c Release
      - name: Build Printer
        run: cd tools/TTF-Printer/TTF-Printer && dotnet build -c Release
      - name: Package Printer
        run: cd tools/TTF-Printer/TTF-Printer/bin/Release/netcoreapp* && zip -qq -r ../TTF-Printer.zip .
      - name: Package Taxonomy Service
        run: cd tools/TaxonomyService/TaxonomyService/bin/Release/netcoreapp* && zip -qq -r ../TaxonomyService.zip .
      - name: Package Artifacts
        run: cd artifacts && zip -qq -r ../artifacts.zip .
      - name: Release Printer
        uses: djnicholson/release-action@v2.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: TTF-Printer.zip
          file: tools/TTF-Printer/TTF-Printer/bin/Release/TTF-Printer.zip
          release-name: ${{ env.RELEASE_NAME }}
          tag-name: ${{ env.TAG_NAME }}
      - name: Release Taxonomy Service
        uses: djnicholson/release-action@v2.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: TaxonomyService.zip
          file: tools/TaxonomyService/TaxonomyService/bin/Release/TaxonomyService.zip
          release-name: ${{ env.RELEASE_NAME }}
          tag-name: ${{ env.TAG_NAME }}
      - name: Release Artifacts
        uses: djnicholson/release-action@v2.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: artifacts.zip
          file: artifacts.zip
          release-name: ${{ env.RELEASE_NAME }}
          tag-name: ${{ env.TAG_NAME }}
